---
- name: Install Vector package
  become: true
  ansible.builtin.yum:
    name: "{{ vector_package_url }}"
    state: present
  tags: vector
- name: Config for Vector
  become: true
  template:
    src: "vector.yml.j2"
    dest: vector.yml
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  tags: vector
- name: Create systemd unit
  become: true
  template:
    src: "templates/vector.service.j2"
    dest: "/etc/systemd/system/vector.service"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  tags: vector
- name: Start service
  become: true
  systemd:
    name: vector
    state: started
    daemon_reload: true
  tags: vector
